#!/usr/bin/env bash
chef-server-ctl reconfigure

if [[ -f /etc/opscode/chef-validator.pem ]]; then
  cp /etc/opscode/chef-validator.pem /var/www/chef-validator.pem
  chmod 644 /var/www/chef-validator.pem
else
  echo "Couldn't find /etc/chef/chef-validator.pem" >&2
fi

if [[ ! -f /etc/chef/validator.pem ]]; then
  cp /etc/opscode/chef-validator.pem /etc/chef/validation.pem
fi

# On the wbench, Apache listens on 80, switch Chef to a different port
sed -i /var/opt/opscode/nginx/etc/nginx.conf -e 's!listen 80!listen 81!'
sleep 5

# Trust the Chef server
if [[ ! -d /home/cumulus/.chef/trusted_certs ]]; then
  mkdir -p /home/cumulus/.chef/trusted_certs
fi
cp /var/opt/opscode/nginx/ca/wbench.lab.local.crt /home/cumulus/.chef/trusted_certs/

# Set up cumulus user. Use wrapper script because knife prompts for a password
/usr/local/sbin/knife_configure.expect

exit 0
