#!/usr/bin/env bash
set -x

chef-server-ctl reconfigure

if [[ -f /etc/opscode/cumulus-validator.pem ]]; then
  cp /etc/opscode/cumulus-validator.pem /var/www/chef-validator.pem
  chmod 644 /var/www/chef-validator.pem
else
  echo "Couldn't find /etc/opscode/cumulus-validator.pem" >&2
fi

if [[ ! -f /etc/chef/validation.pem ]]; then
  cp /etc/opscode/cumulus-validator.pem /etc/chef/validation.pem
fi

# On the wbench, Apache listens on 80, switch Chef to a different port
# sed -i /var/opt/opscode/nginx/etc/nginx.conf -e 's!listen 80!listen 81!'
# sleep 5

# Trust the Chef server
if [[ ! -d /home/cumulus/.chef/trusted_certs ]]; then
  mkdir -p /home/cumulus/.chef/trusted_certs
fi
chmod 0755 /home/cumulus/.chef

# Set up cumulus user.
chef-server-ctl user-create cumulus Rocket Turtle cumulus@cumulusnetworks.com CumulusLinux! --filename /home/cumulus/.chef/cumulus.pem
chef-server-ctl org-create cumulus "Cumulus Networks" --association_user cumulus --filename /etc/opscode/cumulus-validator.pem

cp /var/opt/opscode/nginx/ca/wbench.lab.local.crt /home/cumulus/.chef/trusted_certs/


exit 0
