#!/bin/bash


set -e

# check if cumulus user exists
getent passwd 'cumulus' > /dev/null 2>&1 && ret=true

if $ret; then
  echo "Found cumulus user. Continue with install"
else
  echo "Cumulus user not found. Check if user 'cumulus' exists"
  exit 1
fi


example_ospf_dir='/home/cumulus/example-ospfunnum-puppet'

echo "Git clone example-ospfunnum-puppet"
git clone https://github.com/CumulusNetworks/example-ospfunnum-puppet.git $example_ospf_dir


echo "Cd into /home/cumulus/example-ospfunnum-puppet"
cd $example_ospf_dir
mkdir templates

echo "execute librarian to install puppet modules"
librarian-puppet install

echo "symlink puppet files from ospfunnum-puppet dir to /etc/puppet"
dirlocs=(files manifests modules templates)

echo "remove puppet files in /etc/ that will be overriding"
for i in "${dirlocs[@]}"
do
  rm -rf /etc/puppet/$i
done


for i in "${dirlocs[@]}"
do
  ln -s  $example_ospf_dir/$i /etc/puppet/$i
done

echo "change ownership of example-ospfunnum-puppet to cumulus"
chown -R cumulus:cumulus $example_ospf_dir


