#!/bin/bash

set -e

# copy correct topology.dot for /var/www/topology.dot
ln -fs /var/www/topology-clos-2lt22s.dot /var/www/topology.dot

# copy topology.dot for ptmd to proper directory
cp -f /var/www/topology.dot /home/cumulus/ansibledemos/roles/common/files

exit 0
