#!/usr/bin/env bash

ISOURL=http://mirror.cwb.cumulusnetworks.com/vmware/VMware-esxi.tar
ISOMD5SUM=24eb965e4405ba1e9dad953b9042525a
ISOTMP=/tmp/vmware-esxi.tar
ISOMNT=/mnt/esxicd
PXEDIR=/var/lib/tftpboot/pxe
ESXDIR=esxi55
BOOTCFG=$PXEDIR/$ESXDIR/boot.cfg
OVFTOOLURL=http://mirror.cwb.cumulusnetworks.com/vmware/VMware-ovftool-4.0.0-2301625-lin.x86_64.bundle
OVFTOOLTMP=/tmp/ovftool.bundle

# download esxi iso
if [ -f $ISOTMP ]; then
	rm $ISOTMP
fi
wget $ISOURL -O $ISOTMP

# check md5sum
DOWNLOADMD5SUM=($(md5sum $ISOTMP))
if [ "$DOWNLOADMD5SUM" != "$ISOMD5SUM" ]; then
    echo "** ESXi MD5 do not match:"
    echo "** Download $DOWNLOADMD5SUM"
    echo "** Expected $ISOMD5SUM"
    exit 1
fi

# folder for esxi installer
if [ -d $PXEDIR/$ESXDIR ]; then
    rm -rf $PXEDIR/$ESXDIR
fi
mkdir -p $PXEDIR/$ESXDIR

# extract iso
echo "Extracting ESXi CD"
#mkdir -p $ISOMNT
#mount -o loop,ro $ISOTMP $ISOMNT
#rsync -a $ISOMNT/ $PXEDIR/$ESXDIR/
#umount $ISOMNT
tar xvf $ISOTMP -C $PXEDIR/$ESXDIR
echo "Extract complete"

# edit ESXi boot.cfg

# remove slashes
sed -i $BOOTCFG -e "s#/##g"

# add prefix
echo "prefix=$ESXDIR/" >> $BOOTCFG

# change title
sed -i $BOOTCFG -e "s#Loading ESXi installer#Loading Cumulus CW ESXi installer#g"

# install ovftool
wget $OVFTOOLURL -O $OVFTOOLTMP
sudo sh -c 'TERM=dumb VMWARE_EULAS_AGREED=yes sh /tmp/ovftool.bundle --console --required'

echo *****************************************************
echo Workbench host OS package: VMWare ESXi 5.5
echo
echo OS install files have been added to /var/lib/tftpboot
echo You can install an OS on a host using:
echo
echo $ cwng-pxehelper -s server1 -o esxi55 -n
echo
echo *****************************************************

exit 0
