#!/usr/bin/env bash

set -e

# duplicate wbench provided SSH keys to root user
if [ ! -e /root/.ssh ]; then
    cp -r /home/cumulus/.ssh /root/.ssh
fi

# copy public key to web root
if [ ! -f /var/www/authorized_keys ]; then
    cp /root/.ssh/id_rsa.pub /var/www/authorized_keys
fi

cat /var/www/authorized_keys >> /root/.ssh/authorized_keys
cat /var/www/authorized_keys >> /home/cumulus/.ssh/authorized_keys

# clone the example-ztp-scripts
if [ ! -d "/home/cumulus/example-ztp-scripts" ]; then
    git clone https://github.com/CumulusNetworks/example-ztp-scripts.git /home/cumulus/example-ztp-scripts
fi

chown -R cumulus:cumulus /home/cumulus/

exit 0
