#!/bin/bash
set -e
#installing sflow-rt
/usr/bin/wget http://www.inmon.com/products/sFlow-RT/sflow-rt.tar.gz -O /tmp/sflow-rt.tar.gz
tar -C /usr/local/ -xvzf /tmp/sflow-rt.tar.gz

update-rc.d sflow-rt defaults
if [ -e /usr/bin/ovs-vsctl ]; 
  then update-rc.d sflowovsd defaults; 
fi 
echo "
_sflow._udp     30      SRV     0 0 6343 wbench
_sflow._udp     30      TXT     (
"txtvers=1"
"sampling.1G=64"
"sampling.10G=128"
"sampling.40G=128"
"polling=10"
) " >> /etc/bind/zones/db.lab.local
service bind9 restart

#/etc/init.d/sflow-rt restart
/usr/sbin/a2enmod proxy_html
# a2enconf /var/www/sflow-rt-cumulus/sflow-rt.conf
ln -s /var/www/sflow-rt-demo/sflow-rt.conf /etc/apache2/conf.d/sflow-rt.conf
/etc/init.d/apache2 reload

exit 0
