#!/bin/bash
set -e

# check if cumulus user exists
getent passwd 'cumulus' > /dev/null 2>&1 && ret=true

if $ret; then
  echo "Found cumulus user. Continue with install"
else
  echo "Cumulus user not found. Check if user 'cumulus' exists"
  exit 1
fi

example_ospf_dir='/home/cumulus/example-ospfunnum-chef'

if [ ! -d $example_ospf_dir ]; then
  echo "Git clone example-ospfunnum-chef"
  git clone https://github.com/CumulusNetworks/example-ospfunnum-chef.git $example_ospf_dir
fi

echo "Cd into /home/cumulus/example-ospfunnum-chef"
cd $example_ospf_dir

echo "install chef librarian"
bundle install

echo "execute librarian to install Chef cookbooks"
librarian-chef install

echo "upload nodes, data bags, cookbooks and roles"
WBENCHCLASS=`jq -r '.[] | .workbench.wbench_class_base' /var/www/wbench.json`

knife ssl fetch

for node in nodes/$WBENCHCLASS/*.json;do
  knife node from file $node
done

for databag in interfaces;do
  knife data bag create $databag
done
knife data bag from file interfaces data_bags/interfaces/$WBENCHCLASS

for cookbooks in cookbooks site-cookbooks;do
  knife cookbook upload -o $cookbooks --all
done

knife role from file roles/switch.json

echo "change ownership of example-ospfunnum-chef to cumulus"
chown -R cumulus:cumulus $example_ospf_dir

exit 0
